# Generated by Django 2.2.1 on 2019-05-20 19:54

import datetime
from django.db import migrations, models
import mdeditor.fields
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_timeaxi'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='名称')),
                ('image', stdimage.models.StdImageField(upload_to='path/to', verbose_name='传图片')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '传图片',
                'verbose_name_plural': '传图片',
            },
        ),
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ['-create_time'], 'verbose_name': '博客', 'verbose_name_plural': '博文'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '文章分类', 'verbose_name_plural': '文章分类'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-create_time'], 'verbose_name': '评论管理', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': '标签页', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterModelOptions(
            name='timeaxi',
            options={'verbose_name': '时间轴', 'verbose_name_plural': '时间轴'},
        ),
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=mdeditor.fields.MDTextField(default='', verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tags', verbose_name='文章标签'),
        ),
    ]
